steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: [ "package", "-Dmaven.test.skip=true" ]
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloudbuildgcp:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloudbuildgcp:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cloudbuildgcp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cloudbuildgcp:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
images:
  - 'gcr.io/$PROJECT_ID/cloudbuildgcp:$COMMIT_SHA'
